### ISSUE TITLE
[Bug] Hunter Mark UP Spam

### ISSUE THREAD

**Issue by Starlynk1** [Vae2009/ConROC_Hunter#2]
Getting spammed with Hunter Mark Up in the chat window. Looked for somewhere to turn that off but cant' find anything in the Hunter Spells window.

**Comment by Starlynk1** [comment]
Is this a debug print line that didn't get turned off?

**Comment by Vae2009** [comment]
Well crap...
That's custom, it costs more! Fixed in just a moment.

**Comment by Starlynk1** [comment]
Thanks
