### ISSUE TITLE
[Feature Request/BUG?] Add Auto Shot to Hunter Window

### ISSUE THREAD

**Issue by Starlynk1** [Vae2009/ConROC_Hunter#3]
Could you add Auto Shot to the Hunter Window so we can choose to disable the message if not having it on our toolbar and to not remind us to use it.

Those of us who use macros just use /startattack and that turns on Auto Shot.

**Comment by Starlynk1** [comment]
Auto shot is always showing as needing to be used even while auto shot is active. So at this point, not sure if this is a bug or something else.

**Comment by Vae2009** [comment]
Ya, I was just looking at this. There is a Auto shot detector but it is about 50% effective atm. I may put a option in the window. Give me a little time.

**Comment by Vae2009** [comment]
Added Auto Shot to Spellmenu as well as fixed Autoshot notifier flag. v1.15.14
